// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    HeaderCom: typeof import('./src/components/HeaderCom.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideMenu: typeof import('./src/components/SideMenu.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
