// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IEpArrowLeft: typeof import('~icons/ep/arrow-left')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
